Kaisei-Information-Tools/KITs

apa.html, assets/css/apa.css, assets/js/apa.js
- APAスタイル作成結果を`textarea`に表示する
- APAスタイル作成結果をローカルストレージ(`apa-result`)に保存する
- バグチェック
- 他環境でデザインが崩れていないか
- コードの持続性・改善点
特になし
=> APAスタイル作成ツールの機能追加

apa.html, assets/css/apa.css, assets/css/base.css, assets/js/apa.js
- APA作成が書籍・学術誌に対応
- APA作成ツールに関するリファクタリング
- APA作成フォームのplaceholder追加
- バグチェック
- デザインに関して
base.cssを少しだけいじったためどこかで影響が出ているかもしれないです
=> :sparkles: feat: APAスタイル書籍・学術誌対応

about.html, apa.html, calculator.html, clock.html, index.html, links.html, navbar.html, navbar_test.html, number.html, terms.html, timer.html, todo.html, vertical.html
- ナビゲーションバーをテンプレートにしてJavascriptから呼び出すようにした
- 問題はないはず
#22
=> :sparkle: feat: ナビゲーションバーのテンプレート化

assets/css/stopwatch.css, assets/js/stopwatch.js, stopwatch.html
- ストップウォッチ機能の追加
- 基礎的なラップ機能を追加
- 使い心地
- Issue: #24
- アイコンはまだなのでURL直打ちで入れます
=> ストップウォッチ追加

assets/css/pomodoro.css, assets/js/pomodoro.js, pomodoro.html
- pomodoro.htmlを追加
- それをJekyllに対応
- バグチェック
- コードの美しさ
- Issueは @Sota000-1 が作ってなかったのでないです。作業するときはIssueを作ってからにしたほうがいいと思います。
=> :sparkles: feat: ポモドーロ時計を追加

Gemfile, _config.yml
=> :sparkles: feat: サイトマップを追加（検索エンジン最適化のため）

_layouts/default.html, _site/assets/css/links.css, _site/assets/css/pomodoro.css, _site/assets/js/pomodoro.js, _site/pomodoro.html, assets/css/base.css, index.html
- アンケートのお知らせ機能を追加
- バグチェック
- 表示方法などでもっといいものがあれば教えてほしい
- コードの美しさ
- どこでもいつでも何度でもでてくるのでけっこううざいかもしれない。
=> :sparkles: feat: アンケートのお知らせトーストを追加

_layouts/default.html
=> :sparkles: feat: アンケート通知を再表示

apa.html, assets/css/apa.css, assets/js/apa.js
- apa関連ファイルのリファクタリング
- APAスタイル作成にあたるそれぞれの必須項目の可視化
- APAスタイル作成時、所定の文字列を斜体にする
- コピー時には書式付きコピーにも対応
- バグチェック
- Close #37
=> :sparkles: feat: APAスタイル必須項目可視化&斜体対応

index.html
- グループ分け、数字読み方変換、電卓をsvgアイコンに変更
- ストップウォッチとポモドーロ時計をトップページに追加
- ストップウォッチとポモドーロ時計の説明書き
- Close #24 
- 時計、APA、縦書き、todoに関してはsvgアイコンに改善の余地があるのでまだ変更していません。
=> ✨ feat: 一部アイコンをSVGに変更&ストップウォッチとポモドーロ時計のトップページへの追加

_layouts/default.html
=> Googleアナリティクスのタグを実装

assets/js/calculator.js
=> ✨ feat: 電卓の桁数を増加

assets/js/apa.js
- 著者名と日付の間に半角スペースを追加
- 著者名が入力されていないかつサイト名が入力されている場合の処理を修正
- バグチェック
特になし
=> :sparkles: feat: APAスタイルで間違っていた部分を修正

apa.html, assets/js/apa.js
- URLからの情報自動取得機能を追加
- バグチェック
- 脆弱性
- コードの美しさ
- @YouTuber-repopo が作成してくれないので自分で作りました
=> ✨ feat: 自動取得機能の追加

assets/js/apa.js
- #56 の続き
- 「取得できませんでした」ではなく空欄になるようにした
- 特になし
=> 🐛 fix: 取得できなかったときに空欄にするようにする

assets/css/stopwatch.css, assets/js/stopwatch.js, stopwatch.html
- stopwatch.htmlのfooterのCSSを調節
- CSSのみの変更なのでレビューは確認のみでいいです
- Issue: #46
=> ✨ feat: ストップウォッチのフッターを調節

assets/css/base.css, assets/js/clock.js
=> ✨ feat: 時計の色数を追加

assets/css/base.css, assets/js/clock.js
- 時計の色数をもっと追加した。
- 追加した色：sapphire
ここまでの色の合計：
ノーマル
rainbow
golden
silver
platinum
ruby
topaz
emerald
amethyst
diamond
sapphire
計11色
=> ✨ feat: 更に色数を増加

assets/css/base.css, assets/js/clock.js
=> ✨ feat: 色数をさらに追加

_layouts/default.html
- _layouts/default.htmlのフッターの組織名をKaisei Information TechnologiesからKaisei Information Technology for supportに変更
特になし
特になし
=> :sparkles: feat: フッターの組織名をKaisei Information Technology for supportに変更

assets/css/count.css, assets/js/count.js, count.html
- カウンターを追加（担当： @Sota000-1 ）
- コードの美しさ
- バグチェック
=> ✨ feat: カウンターの追加

assets/css/count.css, assets/js/count.js, count.html
- カウンターのデザイン整形
- 数値表示欄のcontenteditable削除
- 数値表示欄クリック時の挙動変更
- リファクタリング
- バグチェック
- なし
=> :sparkles: feat: カウンターのデザイン変更

assets/css/base.css, assets/css/index.css, assets/css/number.css
やったこと・できるようになったことを箇条書き形式で書いてください。\
例:
- base.css、index.css、number.cssを修正
- バグチェック
- 脆弱性
- コードの美しさ
- チェックはもうしたので勝手にマージします。
=> ✨ feat: 読み方変換ツールのCSSのバグを修正

_layouts/default.html
=> :sparkles: feat: 右下のトーストを再調査フォームに変更

_layouts/default.html
=> :sparkles: feat: トーストのチェックボックスのdisabledを解除

other_npo.html
- other_npo.htmlの更新
- バグチェック
- なし
=> ✨ feat: other_npo.htmlの更新

assets/css/base.css, assets/css/latex.css, assets/js/latex.js, latex.html
- latex.htmlにLaTeXエディタを追加した。
- バグチェック
- 脆弱性
- コードの美しさ
=> ✨ feat: LaTeXエディタを追加

_layouts/default.html, other_npo.html
=> ✨ feat: default.htmlとother_npo.htmlの更新

assets/css/timer.css, assets/js/timer.js, timer.html
- タイマーの多段階化
- 音 on/off機能の追加
- 全体的なUIの変更
- バグチェック
- デザインチェック
- 機能の改善点
- Issue: #28 
- 旧Pull Request: #31 
- ローカルストレージ保存はまだしていません
=> :sparkles: feat: タイマー多段階化

other_npo.html
- other_npo.htmlのIt+部分をコメントアウト
=> :sparkles: feat: It+のリンクを削除

assets/js/timer.js, timer.html
- `startAllTimer`, `stopAllTimer`関数の処理を`assets/js/timer.js`に移動した
- startAllボタンを押下した際に一度`stopAllTimer`関数を呼んでから`startAllTimer`関数を呼ぶようにした
- バグチェック
- Issue: #82
- startAllボタンを連打すると、押すたびに1秒タイマーが更新されます
=> :bug: fix: タイマーの進む速さが誤っているバグを修正 close #82

other_npo.html
- モルフォのリンクの追加
- めんどりの説明文ついか
- バグチェック
- 語字
- なし
=> ✨ feat: モルフォのリンクの追加とめんどりの説明文のついか

other_npo.html
=> 💄 feat: 他NPOリンクの接頭語を削除

assets/css/base.css, assets/js/clock.js, index.html
- index.htmlの画像にwidthを追加した
- バグチェック
- 脆弱性
- コードの美しさ
=> ✨ feat: 画像にwidthを追加

assets/css/base.css, assets/js/clock.js
- PMより提案のあった10色を追加
- バグチェック
- 脆弱性
- コードの美しさ
追加した色は以下のとおりです
- obsidian
- aquamarine
- quartz
- bismuth
- watermelon tourmaline
- mystic topaz
- cats eye
- alexandrite
- amber
- pearl
スペースはキーチェインに使えないためスペース抜きで打ってください
=> ✨ feat: 提案のあった色をさらに追加

Gemfile.lock, assets/css/kundoku.css, kundoku.html
- 訓読文エディタを追加
- バグチェック
- 脆弱性
- コードの美しさ
=> ✨ feat: 訓読文エディタを追加

other_npo.html
- 先生を訪ねて三千里のリンクを修正
- バグチェック
- ミスしてないか
- なし
=> ✨ feat: 先生を訪ねて三千里のリンクを修正、Lilla!のリンクの追加

_layouts/default.html, assets/favicon/site.webmanifest, sw.js
- PWA(Progressive Web Application)にする
- 一部ページを、一度アクセスすればオフライン時でも動作するように対応
- サービスワーカーを作成
- バグチェック
- 脆弱性
- コードの美しさ
- オフライン対応してもオフラインの場合ウェブサイトはInterClass Filtering Serviceによってブロックされる可能性あり
=> ✨ feat: PWA化・オフライン対応

assets/css/group.css
- assets/css/group.cssのスタイルを修正
- バグチェック
- 脆弱性
- コードの美しさ
=> ✨ feat: グループ分けツールではみ出る問題を修正

other_npo.html
=> ✨ feat: こじょぷろ追加

sw.js
- sw.jsを更新
- バグチェック
- 脆弱性
- コードの美しさ
=> ✨ feat: キャッシュの方法を更新

assets/js/group.js
- group.jsにフッターのpositionを設定する関数を追加した．
- バグチェック
- Issue: #104 
- 他のファイルがどういうシステムでposition: fixedになっているか不明．
=> :bug: fix: グループ分けツールでフッターが下端にならない問題を修正する

index.html
=> ✨ feat:  Update index.html

sw.js
- sw.jsにconversion系を追加
- cacheをv3に変更
=> ✨ feat: キャッシュ対象に単位変換を追加
